Language support person name
hellohaptik/chatbot_ner pull request #380
Opened 2020-11-06 05:35 UTC by ashutoshsingh0223

## JIRA Ticket Number

JIRA TICKET: https://hello-haptik.atlassian.net/browse/ML-2048

## Description of change
- Support name detection for indic languages along with hindi

## Checklist (OPTIONAL):

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-11-06 05:35 UTC, haptik-deployment commented on language_utilities/constant.py
> +
W391 blank line at end of file

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +           'ஊறவைத்தது', 'விடுங்கள்', 'மகள் விடுப்பு', 'சூளை', 'விடுங்கள்', 'fucker', 'கட்டை', 'காண்டு', 'செய்யப்பட்டது',
E501 line too long (120 > 119 characters)

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +           'கெக்கோவின் ஈரமான தள்ளுபடி', 'மெத்தை முலைக்காம்பு முடியின் ஜூன்', 'சல்லு ஹூட்டில் மூழ்கிவிட்டார்', 'குந்தமா',
E501 line too long (120 > 119 characters)

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +           'ಸಾಸ್ ಅನ್ನು ನಿರ್ವಹಿಸಿ', 'ಚುಚ್ಚಿದ', 'ಸ್ನಗ್ಲ್', 'ಸ್ನಿಫರ್', 'ಕಡಲೆ', 'Ch ೋಡ್ರಾ', 'ಚು ಭಗತ್', 'ಬಿಡಿ', 'ಮೊಲೆತೊಟ್ಟು',
E501 line too long (120 > 119 characters)

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +           'अपनी मा को जा चूस', 'भें के लॉड', 'भें के टक्के: गो आंड सक युवर सिस्टर’स बॉल्', 'अबला नारी तेरा बुबले भारी',
E501 line too long (120 > 119 characters)

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +           'ज्या', 'ज्या', 'जीस', 'ज्या', 'कोठे', 'म्हणून', 'जसे', 'ते', 'पर्यंत', 'मग', 'प्रकार', 'तीन', 'तीन', 'तेरा',
E501 line too long (120 > 119 characters)

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +           'नुके', 'नाही', 'नाही', 'स्थूल', 'तळ', 'आहे', 'चालू', 'पहिला', 'संपूर्ण', 'चालू', 'पुन्हा', 'केले', 'पुस्तक',
E501 line too long (120 > 119 characters)

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +           'किंवा', 'हे', 'या', 'ठेवा', 'राहिले', 'आहेत', 'ऱ्वासा', 'च्या साठी', 'च्या साठी', 'परंतु', 'आणि', 'आणि इतर',
E501 line too long (120 > 119 characters)

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +           'श्रेणी', 'तो', 'तेथे', 'तिथेच', 'विषयावर', 'Vuh', 'ते', 'करू शकता', 'करू शकता', 'सगळ्यांकडून', 'सर्व', 'सह',
E501 line too long (120 > 119 characters)

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +           'యొక్క', 'కు', 'ఎవరైనా', 'Who', 'ఏది', 'పోయింది', 'ఇల్లు', 'ఎప్పుడు', 'ఎక్కడ', 'వెళ్ళండి', 'ఉన్నంత', 'జిన్',
E501 line too long (120 > 119 characters)

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +           'ఎవరిని', 'ఎవరిని', 'జిస్', 'ఎవరిని', 'ఎక్కడ', 'గా', 'వంటి', 'అది', 'వరకు', 'అప్పుడు', 'రకం', 'మూడు', 'మూడు',
E501 line too long (120 > 119 characters)

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +           'நடந்தது', 'இருக்கிறது', 'ஹு', 'ஹோ', 'நடக்கும்', 'வேண்டும்', 'நிகழ்கிறது', 'நடக்கும்', 'முடிந்தது', 'நான்'],
E501 line too long (120 > 119 characters)

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +    'gu': ['તેથી', 'આપણું', 'ખાણ', 'આપણો', 'હવે', 'અંદર', 'e.t.c', 'તમે', 'અને તેથી વધુ', 'માં', 'તેમના', 'આ', 'આ', 'આ',
E501 line too long (120 > 119 characters)

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +           'અંદર', 'પરંતુ', 'જો તરીકે', 'હું', 'માં', 'જો', 'આ', 'અહીં', 'આ માત્ર', 'અથવા', 'આ', 'આ', 'રાખવું', 'રહ્યા',
E501 line too long (120 > 119 characters)

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +           'વહુ', 'તેઓ', 'કરી શકો છો', 'કરી શકે છે', 'બધા માંથી', 'બધા', 'સાથે', 'સંપૂર્ણ', 'જમા', 'બધા', 'થી', 'ઓ / ઓ',
E501 line too long (120 > 119 characters)

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +           'સાથે', 'માત્ર', 'બન્યું', 'હુઈ', 'બન્યું', 'છે', 'હુ', 'હો', 'થાય છે', 'હશે', 'થાય છે', 'થાય છે', 'થઈ ગયું',
E501 line too long (120 > 119 characters)

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +           'ಯಾರಾದರೂ', 'Who', 'ಇದು ಒಂದು', 'ಗಾನ್', 'ಮನೆ', 'ಯಾವಾಗ', 'ಎಲ್ಲಿ', 'ಹೋಗಿ', 'ಅಷ್ಟೇ', 'ಜಿನ್', 'ಯಾರನ್ನು', 'ಯಾರನ್ನು',
E501 line too long (120 > 119 characters)

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +           'ಎರಡು', 'ಇವರಿಂದ', 'ಅಲ್ಲ', 'ನ್ಯೂಕ್', 'ಇಲ್ಲ', 'ಇಲ್ಲ', 'ಒಟ್ಟಾರೆಯಾಗಿ', 'ಕೆಳಗೆ', 'ಇದೆ', 'ಆನ್', 'ಪ್ರಥಮ', 'ಸಂಪೂರ್ಣ',
E501 line too long (120 > 119 characters)

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +           'ಆನ್', 'ಮತ್ತೆ', 'ತಯಾರಿಸಲಾಗುತ್ತದೆ', 'ಪುಸ್ತಕ', 'ತುಂಬಾ', 'ನಂತರ', 'ಬಾಲಾ', 'ಸಂಪೂರ್ಣವಾಗಿ', 'ತುಂಬಾ', 'ಒಳಗೆ', 'ಆದರೆ',
E501 line too long (120 > 119 characters)

2020-11-06 05:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +    'hi': ['अत', 'अपना',  'अपनी',  'अपने',  'अभी',  'अंदर',  'आदि',  'आप',  'इत्यादि',  'इन ',  'इनका',  'इन्हीं',  'इन्हें',  'इन्हों',  'इस',  'इसका',  'इसकी',  'इसके',  'इसमें',  'इसी',  'इसे',  '
E241 multiple spaces after ','
E501 line too long (1454 > 119 characters)

2020-11-06 05:55 UTC, haptik-deployment commented
UNIT TESTS FAILED... Please resolve issues

2020-11-06 09:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/name_detection.py
> +                pos_words = [word[0] for word in tagged_names if word[1].startswith('NN') or
W504 line break after binary operator

2020-11-06 09:35 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/name_detection.py
> +                pos_words = [word[0] for word in tagged_names if word[1].startswith('NOUN') or
W504 line break after binary operator

2020-11-06 09:35 UTC, haptik-deployment commented on lib/nlp/spacy_utils.py
> +import six
W1618 [34mimport missing `from __future__ import absolute_import`[0m

2020-11-06 09:48 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/hindi_const.py
> +           'वहीं', 'वाले', 'वुह', 'वे', 'सकता', 'सकते', 'सबसे', 'सभी', 'साथ', 'साबुत', 'साभ', 'सारा', 'से', 'सो', 'संग',
E501 line too long (120 > 119 characters)

2020-11-06 09:54 UTC, haptik-deployment commented
UNIT TESTS FAILED... Please resolve issues

2020-11-06 09:59 UTC, haptik-deployment commented
UNIT TESTS FAILED... Please resolve issues

2020-11-06 10:18 UTC, haptik-deployment commented
UNIT TESTS FAILED... Please resolve issues

2020-11-09 06:32 UTC, haptik-deployment commented on ner_v1/detectors/textual/name/tests/test_name_detection.py
> +            self.data['mocked_values']):
E129 visually indented line with same indent as next logical line

2020-11-09 06:33 UTC, haptik-deployment commented
UNIT TESTS FAILED... Please resolve issues

2020-11-09 06:39 UTC, haptik-deployment commented
UNIT TESTS FAILED... Please resolve issues

2020-11-09 06:44 UTC, haptik-deployment commented
UNIT TESTS FAILED... Please resolve issues

2020-11-09 06:58 UTC, haptik-deployment commented
UNIT TESTS FAILED... Please resolve issues

2020-11-09 08:58 UTC, haptik-deployment commented
UNIT TESTS FAILED... Please resolve issues

2020-11-09 09:59 UTC, haptik-deployment commented
UNIT TESTS FAILED... Please resolve issues

2020-11-09 10:04 UTC, haptik-deployment commented
UNIT TESTS FAILED... Please resolve issues

2020-11-10 04:58 UTC, ankur09011 requested changes

2020-11-10 04:58 UTC, ankur09011 commented on lib/nlp/spacy_utils.py
> +    def tag(self, text, language):
add documentation for this

2020-11-10 04:58 UTC, ankur09011 commented on lib/nlp/spacy_utils.py
> +    def tokenize(self, text, language):
add documentation for this

2020-11-10 08:16 UTC, ashutoshsingh0223 commented on lib/nlp/spacy_utils.py
> +    def tag(self, text, language):
Done

2020-11-10 08:16 UTC, ashutoshsingh0223 commented on lib/nlp/spacy_utils.py
> +    def tokenize(self, text, language):
Done

2020-11-10 08:39 UTC, haptik-deployment commented on lib/nlp/tests/test_nlp_utils.py
> +from django.test import TestCase
W1618 [34mimport missing `from __future__ import absolute_import`[0m

2020-11-10 08:49 UTC, haptik-deployment commented
UNIT TESTS FAILED... Please resolve issues

2020-11-10 08:54 UTC, haptik-deployment commented
UNIT TESTS FAILED... Please resolve issues

2020-11-10 09:13 UTC, ankur09011 submitted a review, later dismissed

2020-11-12 11:13 UTC, haptik-deployment commented
UNIT TESTS FAILED... Please resolve issues

2020-11-24 17:27 UTC, haptik-deployment commented
UNIT TESTS FAILED... Please resolve issues

2020-11-25 12:58 UTC, haptik-deployment commented
UNIT TESTS FAILED... Please resolve issues

2020-12-02 09:18 UTC, haptik-deployment commented
UNIT TESTS FAILED... Please resolve issues

2020-12-02 10:13 UTC, haptik-deployment commented
UNIT TESTS FAILED... Please resolve issues

2020-12-02 10:29 UTC, ankur09011 approved these changes

2020-12-04 11:50 UTC, haptik-deployment commented on ner_v2/api.py
> +        import pdb;pdb.set_trace()
E702 multiple statements on one line (semicolon)
E231 missing whitespace after ';'

2020-12-04 12:26 UTC, haptik-deployment commented
UNIT TESTS HAVE PASSED... Good To Merge

2020-12-04 15:47 UTC, chiragjn approved these changes

2020-12-04 15:48 UTC, merged